# Generated by Django 4.2.20 on 2025-05-06 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('userEmail', models.CharField(max_length=255)),
                ('userID', models.IntegerField()),
                ('position', models.CharField(max_length=255)),
                ('businessUnit', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('departureDate', models.DateField()),
                ('returnDate', models.DateField()),
                ('date_requested', models.DateField()),
                ('date_needed', models.DateField()),
                ('purpose', models.CharField(max_length=255)),
                ('paymentMode', models.CharField(choices=[('GCASH', 'GCASH'), ('METROBANK', 'METROBANK'), ('CASH', 'CASH')], max_length=50)),
                ('accountNumber', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('table_type', models.CharField(max_length=50)),
                ('rejection_reason', models.TextField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-date_requested'],
            },
        ),
        migrations.CreateModel(
            name='CashReimbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('userEmail', models.CharField(max_length=255)),
                ('userID', models.IntegerField()),
                ('position', models.CharField(max_length=255)),
                ('businessUnit', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('departureDate', models.DateField()),
                ('returnDate', models.DateField()),
                ('date_requested', models.DateField()),
                ('date_needed', models.DateField()),
                ('purpose', models.CharField(max_length=255)),
                ('paymentMode', models.CharField(choices=[('GCASH', 'GCASH'), ('METROBANK', 'METROBANK'), ('CASH', 'CASH')], max_length=50)),
                ('accountNumber', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('table_type', models.CharField(max_length=50)),
                ('rejection_reason', models.TextField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-date_requested'],
            },
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('locFrom', models.CharField(blank=True, max_length=100, null=True)),
                ('locTo', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('purchase_number', models.IntegerField(blank=True, null=True)),
                ('particulars', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('meal_type', models.CharField(blank=True, choices=[('BREAKFAST', 'BREAKFAST'), ('LUNCH', 'LUNCH'), ('DINNER', 'DINNER')], max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Lodging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('check_in', models.DateField(blank=True, null=True)),
                ('check_out', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='CashLiquidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('userEmail', models.CharField(max_length=255)),
                ('userID', models.IntegerField()),
                ('position', models.CharField(max_length=255)),
                ('businessUnit', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('departureDate', models.DateField()),
                ('returnDate', models.DateField()),
                ('date_requested', models.DateField()),
                ('date_needed', models.DateField()),
                ('purpose', models.CharField(max_length=255)),
                ('paymentMode', models.CharField(choices=[('GCASH', 'GCASH'), ('METROBANK', 'METROBANK'), ('CASH', 'CASH')], max_length=50)),
                ('accountNumber', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('table_type', models.CharField(max_length=50)),
                ('rejection_reason', models.TextField(blank=True, max_length=255, null=True)),
                ('cash_advance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liquidations', to='cashadvanceapp.cashadvance')),
            ],
            options={
                'ordering': ['-date_requested'],
            },
        ),
    ]
