# Generated by Django 4.2.20 on 2025-05-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashadvanceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashadvance',
            name='accountNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
