# Generated by Django 4.2.20 on 2025-05-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashadvanceapp', '0002_alter_cashadvance_accountnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashadvance',
            name='departureDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cashadvance',
            name='returnDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cashliquidation',
            name='departureDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cashliquidation',
            name='returnDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cashreimbursement',
            name='departureDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cashreimbursement',
            name='returnDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
