# Generated by Django 4.2.20 on 2025-05-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashadvanceapp', '0003_alter_cashadvance_departuredate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashliquidation',
            name='accountNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cashreimbursement',
            name='accountNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
